/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package icewastedetector;

import com.sun.awt.AWTUtilities;

/**
 *
 * @author ID
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
        AWTUtilities.setWindowOpaque(this, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        movebt = new javax.swing.JLabel();
        preview = new javax.swing.JLabel();
        menufolbt = new javax.swing.JLabel();
        menuhelpbt = new javax.swing.JLabel();
        menufilebt = new javax.swing.JLabel();
        exitbt = new javax.swing.JLabel();
        minibt = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        movebt.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                movebtMouseDragged(evt);
            }
        });
        movebt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                movebtMousePressed(evt);
            }
        });
        getContentPane().add(movebt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 680, 50));

        preview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/preview_06.gif"))); // NOI18N
        getContentPane().add(preview, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 300, 210));

        menufolbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btfol_15.gif"))); // NOI18N
        menufolbt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menufolbtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menufolbtMouseExited(evt);
            }
        });
        getContentPane().add(menufolbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 270, 50));

        menuhelpbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bthelp_17.gif"))); // NOI18N
        menuhelpbt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuhelpbtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuhelpbtMouseExited(evt);
            }
        });
        getContentPane().add(menuhelpbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 270, 50));

        menufilebt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btfile_10.gif"))); // NOI18N
        menufilebt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menufilebtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menufilebtMouseExited(evt);
            }
        });
        getContentPane().add(menufilebt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 270, 50));

        exitbt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/exitbt2_05.gif"))); // NOI18N
        exitbt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitbtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitbtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitbtMouseExited(evt);
            }
        });
        getContentPane().add(exitbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 50, 50));

        minibt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minibt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/minibt2_03.gif"))); // NOI18N
        minibt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minibtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minibtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minibtMouseExited(evt);
            }
        });
        getContentPane().add(minibt, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 60, 50));

        background.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/backgroundonly.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitbtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbtMouseClicked
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_exitbtMouseClicked

    private void minibtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minibtMouseClicked
        // TODO add your handling code here:
        this.setState(MainForm.ICONIFIED);
    }//GEN-LAST:event_minibtMouseClicked

    private void exitbtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbtMouseEntered
        // TODO add your handling code here:
        exitbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/exitbt_05.gif")));
    }//GEN-LAST:event_exitbtMouseEntered

    private void exitbtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbtMouseExited
        // TODO add your handling code here:
        exitbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/exitbt2_05.gif")));
    }//GEN-LAST:event_exitbtMouseExited

    private void minibtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minibtMouseEntered
        // TODO add your handling code here:
        minibt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/minibt_03.gif")));
    }//GEN-LAST:event_minibtMouseEntered

    private void menufilebtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menufilebtMouseEntered
        // TODO add your handling code here:
        menufilebt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btfileh_10.gif")));
    }//GEN-LAST:event_menufilebtMouseEntered

    private void menufilebtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menufilebtMouseExited
        // TODO add your handling code here:
        menufilebt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btfile_10.gif")));
    }//GEN-LAST:event_menufilebtMouseExited

    private void minibtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minibtMouseExited
        // TODO add your handling code here:
        minibt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/minibt2_03.gif")));
    }//GEN-LAST:event_minibtMouseExited

    private void menufolbtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menufolbtMouseEntered
        // TODO add your handling code here:
        menufolbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btfolh_15.gif")));
    }//GEN-LAST:event_menufolbtMouseEntered

    private void menufolbtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menufolbtMouseExited
        // TODO add your handling code here:
        menufolbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btfol_15.gif")));
    }//GEN-LAST:event_menufolbtMouseExited

    private void menuhelpbtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuhelpbtMouseEntered
        // TODO add your handling code here:
        menuhelpbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bthelph_17.gif")));
        
    }//GEN-LAST:event_menuhelpbtMouseEntered

    private void menuhelpbtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuhelpbtMouseExited
        // TODO add your handling code here:
        menuhelpbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bthelp_17.gif")));
    }//GEN-LAST:event_menuhelpbtMouseExited
    int xmouse;
    int ymouse;
    private void movebtMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movebtMouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();        
        int y=evt.getYOnScreen();
        this.setLocation(x-xmouse, y-ymouse);
    }//GEN-LAST:event_movebtMouseDragged

    private void movebtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movebtMousePressed
        // TODO add your handling code here:
        xmouse=evt.getX();
        ymouse=evt.getY();        
    }//GEN-LAST:event_movebtMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel exitbt;
    private javax.swing.JLabel menufilebt;
    private javax.swing.JLabel menufolbt;
    private javax.swing.JLabel menuhelpbt;
    private javax.swing.JLabel minibt;
    private javax.swing.JLabel movebt;
    private javax.swing.JLabel preview;
    // End of variables declaration//GEN-END:variables
}
